import { QuestionValueType } from './Questions.types';

export const QuestionTest = [
  {
    id: 0,
    name: 'test',
    questionNumber: '1번 문제',
    questionTitle: '정답은 4번입니다. 몇번이 정답일까요?',
    question: [
      '1번 - 몇번이 정답일까요?',
      '2번 - 몇번이 정답일까요?',
      '3번 - 몇번이 정답일까요?',
      '4번 - 몇번이 정답일까요?',
      '5번 - 몇번이 정답일까요?',
    ],
    questionResult: 4,
  },
];
export const QuestionValue = <QuestionValueType[]>[
  {
    id: 1,
    name: 'potion',
    questionNumber: '1번 문제',
    questionTitle: `'버려진 해적선 - 비' 맵에서 등장하는 '자석 폭탄'의 쿨타임은 몇 초일까?`,
    question: ['1번 - 30초', '2번 - 35초', '3번 - 40초', '4번 - 45초', '5번 - 50초'],
    questionResult: 3,
  },
  {
    id: 2,
    name: 'potion',
    questionNumber: '2번 문제',
    questionTitle: `스매시 레전드의 랭크 '플래티넘'은 몇 단계까지 있을까?`,
    question: ['1번 - 1단계', '2번 - 2단계', '3번 - 3단계', '4번 - 4단계', '5번 - 5단계'],
    questionResult: 3,
  },
  {
    id: 3,
    name: 'potion',
    questionNumber: '2번 문제',
    questionTitle: `스매시 레전드의 랭크 '플래티넘'은 몇 단계까지 있을까?`,
    question: ['1번 - 1단계', '2번 - 2단계', '3번 - 3단계', '4번 - 4단계', '5번 - 5단계'],
    questionResult: 3,
  },
  {
    id: 4,
    name: 'potion',
    questionNumber: '2번 문제',
    questionTitle: `스매시 레전드의 랭크 '플래티넘'은 몇 단계까지 있을까?`,
    question: ['1번 - 1단계', '2번 - 2단계', '3번 - 3단계', '4번 - 4단계', '5번 - 5단계'],
    questionResult: 3,
  },
  {
    id: 5,
    name: 'potion',
    questionNumber: '2번 문제',
    questionTitle: `스매시 레전드의 랭크 '플래티넘'은 몇 단계까지 있을까?`,
    question: ['1번 - 1단계', '2번 - 2단계', '3번 - 3단계', '4번 - 4단계', '5번 - 5단계'],
    questionResult: 3,
  },
  {
    id: 6,
    name: 'potion',
    questionNumber: '2번 문제',
    questionTitle: `스매시 레전드의 랭크 '플래티넘'은 몇 단계까지 있을까?`,
    question: ['1번 - 1단계', '2번 - 2단계', '3번 - 3단계', '4번 - 4단계', '5번 - 5단계'],
    questionResult: 3,
  },
  {
    id: 7,
    name: 'potion',
    questionNumber: '2번 문제',
    questionTitle: `스매시 레전드의 랭크 '플래티넘'은 몇 단계까지 있을까?`,
    question: ['1번 - 1단계', '2번 - 2단계', '3번 - 3단계', '4번 - 4단계', '5번 - 5단계'],
    questionResult: 3,
  },
  {
    id: 8,
    name: 'potion',
    questionNumber: '2번 문제',
    questionTitle: `스매시 레전드의 랭크 '플래티넘'은 몇 단계까지 있을까?`,
    question: ['1번 - 1단계', '2번 - 2단계', '3번 - 3단계', '4번 - 4단계', '5번 - 5단계'],
    questionResult: 3,
  },
  {
    id: 9,
    name: 'potion',
    questionNumber: '2번 문제',
    questionTitle: `스매시 레전드의 랭크 '플래티넘'은 몇 단계까지 있을까?`,
    question: ['1번 - 1단계', '2번 - 2단계', '3번 - 3단계', '4번 - 4단계', '5번 - 5단계'],
    questionResult: 3,
  },
  {
    id: 10,
    name: 'potion',
    questionNumber: '2번 문제',
    questionTitle: `스매시 레전드의 랭크 '플래티넘'은 몇 단계까지 있을까?`,
    question: ['1번 - 1단계', '2번 - 2단계', '3번 - 3단계', '4번 - 4단계', '5번 - 5단계'],
    questionResult: 3,
  },
  {
    id: 11,
    name: 'potion',
    questionNumber: '1번 문제',
    questionTitle: `'버려진 해적선 - 비' 맵에서 등장하는 '자석 폭탄'의 쿨타임은 몇 초일까?`,
    question: ['1번 - 30초', '2번 - 35초', '3번 - 40초', '4번 - 45초', '5번 - 50초'],
    questionResult: 3,
  },
  {
    id: 12,
    name: 'potion',
    questionNumber: '2번 문제',
    questionTitle: `스매시 레전드의 랭크 '플래티넘'은 몇 단계까지 있을까?`,
    question: ['1번 - 1단계', '2번 - 2단계', '3번 - 3단계', '4번 - 4단계', '5번 - 5단계'],
    questionResult: 3,
  },
  {
    id: 13,
    name: 'potion',
    questionNumber: '2번 문제',
    questionTitle: `스매시 레전드의 랭크 '플래티넘'은 몇 단계까지 있을까?`,
    question: ['1번 - 1단계', '2번 - 2단계', '3번 - 3단계', '4번 - 4단계', '5번 - 5단계'],
    questionResult: 3,
  },
  {
    id: 14,
    name: 'potion',
    questionNumber: '2번 문제',
    questionTitle: `스매시 레전드의 랭크 '플래티넘'은 몇 단계까지 있을까?`,
    question: ['1번 - 1단계', '2번 - 2단계', '3번 - 3단계', '4번 - 4단계', '5번 - 5단계'],
    questionResult: 3,
  },
  {
    id: 15,
    name: 'potion',
    questionNumber: '2번 문제',
    questionTitle: `스매시 레전드의 랭크 '플래티넘'은 몇 단계까지 있을까?`,
    question: ['1번 - 1단계', '2번 - 2단계', '3번 - 3단계', '4번 - 4단계', '5번 - 5단계'],
    questionResult: 3,
  },
  {
    id: 16,
    name: 'potion',
    questionNumber: '2번 문제',
    questionTitle: `스매시 레전드의 랭크 '플래티넘'은 몇 단계까지 있을까?`,
    question: ['1번 - 1단계', '2번 - 2단계', '3번 - 3단계', '4번 - 4단계', '5번 - 5단계'],
    questionResult: 3,
  },
  {
    id: 17,
    name: 'potion',
    questionNumber: '2번 문제',
    questionTitle: `스매시 레전드의 랭크 '플래티넘'은 몇 단계까지 있을까?`,
    question: ['1번 - 1단계', '2번 - 2단계', '3번 - 3단계', '4번 - 4단계', '5번 - 5단계'],
    questionResult: 3,
  },
  {
    id: 18,
    name: 'potion',
    questionNumber: '2번 문제',
    questionTitle: `스매시 레전드의 랭크 '플래티넘'은 몇 단계까지 있을까?`,
    question: ['1번 - 1단계', '2번 - 2단계', '3번 - 3단계', '4번 - 4단계', '5번 - 5단계'],
    questionResult: 3,
  },
  {
    id: 19,
    name: 'potion',
    questionNumber: '2번 문제',
    questionTitle: `스매시 레전드의 랭크 '플래티넘'은 몇 단계까지 있을까?`,
    question: ['1번 - 1단계', '2번 - 2단계', '3번 - 3단계', '4번 - 4단계', '5번 - 5단계'],
    questionResult: 3,
  },
  {
    id: 20,
    name: 'potion',
    questionNumber: '2번 문제',
    questionTitle: `스매시 레전드의 랭크 '플래티넘'은 몇 단계까지 있을까?`,
    question: ['1번 - 1단계', '2번 - 2단계', '3번 - 3단계', '4번 - 4단계', '5번 - 5단계'],
    questionResult: 3,
  },
];
