import { QuestionValueType } from './Questions.types';

export const QuestionTest = [
  {
    id: 0,
    name: 'test',
    questionNumber: '1번 문제',
    questionTitle: '정답은 4번입니다. 몇번이 정답일까요?',
    question: [
      '1번 - 몇번이 정답일까요?',
      '2번 - 몇번이 정답일까요?',
      '3번 - 몇번이 정답일까요?',
      '4번 - 몇번이 정답일까요?',
      '5번 - 몇번이 정답일까요?',
    ],
    questionResult: 4,
  },
];
export const QuestionValue = <QuestionValueType[]>[
  {
    id: 1,
    name: 'potion',
    questionNumber: '1번 문제',
    questionTitle: `'버려진 해적선 - 비' 맵에서 등장하는 '자석 폭탄'의 쿨타임은 몇 초일까?`,
    question: ['1번 - 30초', '2번 - 40초', '3번 - 50초', '4번 - 60초', '5번 - 70초'],
    questionResult: 2,
  },
  {
    id: 2,
    name: 'rank',
    questionNumber: '2번 문제',
    questionTitle: `점령전에서 비허가 제페타 공장 - 석양 맵은 중앙 상단부에 점령지를 자기팀으로 끌어당길 수 있는 스위치가 존재한다. 이 스위치를 점령할려면 얼마만큼의 시간이 걸리는가?`,
    question: ['1번 - 0.75초', '2번 - 1초', '3번 - 1.25초', '4번 - 1.5초', '5번 - 2초'],
    questionResult: 4,
  },
  {
    id: 3,
    name: 'superamor',
    questionNumber: '3번 문제',
    questionTitle: `궁극기를 사용하면 슈퍼아머 상태가 되는데, 이때 공격을 당하면 경직에 걸려서 궁극기가 시전되는 속도가 느려진다.`,
    question: ['O', 'X'],
    questionResult: 1,
  },
  {
    id: 4,
    name: 'battery',
    questionNumber: '4번 문제',
    questionTitle: `궁극기배터리(소)는 캐릭터가 획득하면 일정량의 궁극기게이지를 얻는데, 이때 수치는 얼마인가?`,
    question: ['1번 - 100', '2번 - 200', '3번 - 300', '4번 - 400', '5번 - 500'],
    questionResult: 3,
  },
  {
    id: 5,
    name: 'player',
    questionNumber: '5번 문제',
    questionTitle: `플레이어가 절벽에 떨어질때 난간이 있다면 붙잡는다. 이때 생기는 무적시간은 몇초인가?`,
    question: ['1번 - 0.5초', '2번 - 1초', '3번 - 1.5초', '4번 - 2초', '5번 - 3초'],
    questionResult: 2,
  },
  {
    id: 6,
    name: 'bigPotion',
    questionNumber: '6번 문제',
    questionTitle: `회복물약(대)의 획득하면 일정량의 체력을 회복한다. 회복물약(대) 회복량은 얼마인가?`,
    question: ['1번 - 20%', '2번 - 30%', '3번 - 40%', '4번 - 50%', '5번 - 60%'],
    questionResult: 3,
  },
  {
    id: 7,
    name: 'jumpstep',
    questionNumber: '7번 문제',
    questionTitle: `점령전에서 점프대를 밟으면 해당 플레이어가 점령지에 날아가는데, 이때 플레이어가 실행중인 모든 행동이 강제로 취소된다.`,
    question: ['O', 'X'],
    questionResult: 1,
  },
  {
    id: 8,
    name: 'team',
    questionNumber: '8번 문제',
    questionTitle: `우리팀이 점령지를 점령하기 시작했을때, 점령지 내의 아군의 수가 점령속도에 영향을 끼친다.`,
    question: ['O', 'X'],
    questionResult: 1,
  },
  {
    id: 9,
    name: 'point',
    questionNumber: '9번 문제',
    questionTitle: `점령전에서 1 Point를 획득하기 위한 시간은 몇초인가?`,
    question: ['1번 - 9초', '2번 - 10초', '3번 - 11초', '4번 - 12초', '5번 - 13초'],
    questionResult: 4,
  },
  {
    id: 10,
    name: 'rej',
    questionNumber: '10번 문제',
    questionTitle: `점령 모드의 부활 시간은 몇초인가?`,
    question: ['1번 - 3초', '2번 - 4초', '3번 - 5초', '4번 - 6초', '5번 - 7초'],
    questionResult: 3,
  },
  {
    id: 11,
    name: 'space',
    questionNumber: '11번 문제',
    questionTitle: `'점령전에서 비허가 스페이스독 - 성층권의 맵은 특정 시간이 되면 점령지가 흔들리다가 이동을한다. 이때, 흔들리는 시간은 언제마다인가?`,
    question: [
      '1번 - 20초마다',
      '2번 - 30초마다',
      '3번 - 40초마다',
      '4번 - 50초마다',
      '5번 - 60초마다',
    ],
    questionResult: 2,
  },
  {
    id: 12,
    name: 'levelup',
    questionNumber: '12번 문제',
    questionTitle: `레벨업이나 재능, 각성석으로 공격력 %로 올라간다면, 궁극기게이지 획득량도 그에 비례하여 상승한다.[ex: 오공의 제천대성 40%데미지 증가]`,
    question: ['O', 'X'],
    questionResult: 2,
  },
  {
    id: 13,
    name: 'awakening',
    questionNumber: '13번 문제',
    questionTitle: `일격의 보호막 - 첫 타격 이후 1초 동안 2명/3명 이상의 상대를 적중시키면, 최대 체력의 [?]%/40%만큼 보호막이 생성된다. ?에 들어갈 수치는?`,
    question: ['1번 - 10', '2번 - 15', '3번 - 20', '4번 - 25', '5번 - 30'],
    questionResult: 3,
  },
  {
    id: 14,
    name: 'jump',
    questionNumber: '14번 문제',
    questionTitle: `점프력은 레전드 모두 똑같다.`,
    question: ['O', 'X'],
    questionResult: 2,
  },
  {
    id: 15,
    name: 'ability',
    questionNumber: '15번 문제',
    questionTitle: `궁극 재능의 업그레이드 비용은?`,
    question: [
      '1번 - 2000 크레딧',
      '2번 - 2500 크레딧',
      '3번 - 3000 크레딧',
      '4번 - 3500 크레딧',
      '5번 - 4000 크레딧',
    ],
    questionResult: 5,
  },
  {
    id: 16,
    name: 'legends',
    questionNumber: '16번 문제',
    questionTitle: `레전드 로드에서 레전드 아이콘은 무료 로드에서 얻을 수 있다.`,
    question: ['O', 'X'],
    questionResult: 2,
  },
  {
    id: 17,
    name: 'mode',
    questionNumber: '17번 문제',
    questionTitle: `점령지 점수 3점을 획득하고, 4점을 획득할때 적이 점령지 내에 있다면 끝내기 시간이 발생한다. 이때 일정시간 점령지에서 상대를 몰아내야 게임을 끝낼 수 있는데, 이때 게임을 끝내기까지 걸리는 시간은 1초이다.`,
    question: ['O', 'X'],
    questionResult: 1,
  },
  {
    id: 18,
    name: 'wolfgang',
    questionNumber: '18번 문제',
    questionTitle: `볼프강의 궁극기 '식사시간'은 상대를 스매시했을 경우, 체력이 얼마나 회복되는가?`,
    question: ['1번 - 15%', '2번 - 20%', '3번 - 25%', '4번 - 30%', '5번 - 35%'],
    questionResult: 3,
  },
  {
    id: 19,
    name: 'alice',
    questionNumber: '19번 문제',
    questionTitle: `앨리스의 스킬 '바니바니 마법 폭탄'의 기절 시간은 몇 초인가?`,
    question: ['1번 - 1초', '2번 - 1.25초', '3번 - 1.5초', '4번 - 1.75초', '5번 - 2초'],
    questionResult: 3,
  },
  {
    id: 20,
    name: 'light',
    questionNumber: '20번 문제',
    questionTitle: `연격의 번개 각성의 재사용 대기시간은 몇 초인가?`,
    question: ['1번 - 5초', '2번 - 6초', '3번 - 8초', '4번 - 10초', '5번 - 12초'],
    questionResult: 4,
  },
];
